services:
  postgres:
    image: postgres:16
    container_name: postgres-cursos
    environment:
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: devdb
      POSTGRES_DB: devdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: